graph TB
    session
    internal_a[internal]
    internal_b[internal]
    internal_c[internal]
    internal_d[internal]
    internal_e[internal]
    internal_f[internal]
    notebook_a[notebook]
    notebook_b[notebook]
    user_a[user]
    user_b[user]
    service
    oidc

    subgraph Session
        direction LR
        session --> notebook_a --> internal_a --> internal_f
        session --> internal_b
        session --> oidc
        session --> user_a
    end

    subgraph User
        direction LR
        user_b --> internal_c
    end

    subgraph Service
        direction LR
        service --> internal_d
        service --> notebook_b --> internal_e
    end

    Session ~~~ User ~~~ Service
